---
baseURL: 'http://example.org/'
languageCode: 'en-us'
title: 'Meet Ben Miller'
#theme: 'personal-web'
#themeDir: '/home/ben/WebDev/mysite/html/example/themes/personal-web'

# Main menu
menu:
  main:
      - Name: "Home"
        URL: "/"
        Weight: 0

      - Name: "Projects"
        URL: "/"
        Weight: 1

      - Name: "Hobbies"
        URL: "/"
        Weight: 2

      - Name: "Special Skills"
        URL: "/"
        Weight: 3
---