---
baseURL: 'http://example.org/'
languageCode: 'en-us'
title: 'Meet Ben Miller'

# Main menu
menu:
  main:
      - Name: "Home"
        URL: "#home"
        Weight: 0
        identifier: "home"

      - Name: "Projects"
        URL: "#projects"
        Weight: 1
        identifier: "projects"

      - Name: "Hobbies"
        URL: "#hobbies"
        Weight: 2

      - Name: "Special Skills"
        URL: "#specialskills"
        Weight: 3
---