---
baseURL: 'http://example.org/'
languageCode: 'en-us'
title: 'Meet Ben Miller'

# Main menu
menu:
  home:
      - Name: "Home"
        URL: "#home"
        Weight: 0
        identifier: "home"

      - Name: "Projects"
        URL: "#projects"
        Weight: 1
        identifier: "projects"

      - Name: "Proficiencies"
        URL: "#skills"
        Weight: 2
        identifier: "proficiencies"

      - Name: "Experience"
        URL: "#Experience"
        Weight: 3

      - Name: "Education"
        URL: "#specialskills"
        Weight: 4
---