---
baseURL: 'http://example.org/'
languageCode: 'en-us'
title: 'Meet Ben Miller'
#theme: 'personal-web'
#themeDir: '/home/ben/WebDev/mysite/html/example/themes/personal-web'

# Main menu
menu:
  main:
      - Name: "Home"
        URL: "/"
      - Name: "Projects"
        URL: "/"
      - Name: "Hobbies"
        URL: "/"
      - Name: "Special Skills"
        URL: "/"
---