# This is a basic workflow to help you get started with Actions

name: Build and Deploy HUGO Site 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Set the hugo environment 
    env:
      HUGO_VERSION: 0.92.2

    # Steps represent a sequence of tasks that will be executed as part of the 
    # job
    steps:
      # Install HUGO CLI 
      - name: Install HUGO CLI
        run: |
          apt-get install hugo 
          
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Build site
      - name: Build HUGO site 
        run: |
          hugo \
          --minify \
          -D
          ls

      # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, world!

      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.

      # Run the command set to deploy this webserver
      - name: Deploy to Digital Ocean webserver
        run: |
          echo Deploying to digital ocean. 
